# Generated by Django 3.2.5 on 2021-07-12 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0004_auto_20210712_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='liked',
            field=models.ManyToManyField(blank=True, default=0, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('1', '1'), ('-1', '-1')], default='Like', max_length=10),
        ),
    ]
